// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route.proto

package route;

public final class Route {
  private Route() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_route_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_route_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_route_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_route_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013route.proto\022\005route\"\250\002\n\007Request\022\023\n\006offs" +
      "et\030\001 \001(\003H\000\210\001\001\022\016\n\006origin\030\002 \001(\003\022\023\n\013destina" +
      "tion\030\003 \001(\003\022\014\n\004path\030\004 \001(\t\022\025\n\rresponse_tim" +
      "e\030\005 \001(\003\022\022\n\nchunk_size\030\006 \001(\003\022\032\n\rpackage_i" +
      "ndex\030\007 \001(\003H\001\210\001\001\022\025\n\010time_sum\030\010 \001(\003H\002\210\001\001\022!" +
      "\n\024slow_start_completed\030\t \001(\010H\003\210\001\001\022\021\n\talg" +
      "orithm\030\n \001(\005B\t\n\007_offsetB\020\n\016_package_inde" +
      "xB\013\n\t_time_sumB\027\n\025_slow_start_completed\"" +
      "l\n\010Response\022\016\n\006offset\030\001 \001(\003\022\016\n\006origin\030\002 " +
      "\001(\003\022\023\n\013destination\030\003 \001(\003\022\017\n\007payload\030\004 \001(" +
      "\014\022\014\n\004last\030\005 \001(\010\022\014\n\004path\030\006 \001(\t2>\n\016Request" +
      "Service\022,\n\007request\022\016.route.Request\032\017.rou" +
      "te.Response\"\000B\004H\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_route_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_route_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_route_Request_descriptor,
        new java.lang.String[] { "Offset", "Origin", "Destination", "Path", "ResponseTime", "ChunkSize", "PackageIndex", "TimeSum", "SlowStartCompleted", "Algorithm", "Offset", "PackageIndex", "TimeSum", "SlowStartCompleted", });
    internal_static_route_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_route_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_route_Response_descriptor,
        new java.lang.String[] { "Offset", "Origin", "Destination", "Payload", "Last", "Path", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
